sudo: false
before_install:
  - npm install -g grunt-cli
cache:
  directories:
    - vendor
    - node_modules
script:
  - PATH=$HOME/.local/bin:$PATH script/travis-deploy.sh
env: # IAM: travis-s3
  secure: Q9zRLp8Iyl6yvs1jaF0Q6LqoEErymjVungepcjDeS1nvfA8Ag0aCO0s9iujZtKKrNSZJsX42862QAFYSsht3Et3PwaUgc7S+8EVN77IFFu3Grc2k5gNDSwcVSEM1VsGtoqpZOAuibZHnI7Pv6+e+obCAYUHPeyorzDJGOeTNV1Y=
